# Generated by Django 4.1.3 on 2022-11-30 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_user_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(default='img/user_default.jpg', upload_to='profile_pic/'),
        ),
    ]
