# Generated by Django 4.1.3 on 2022-11-30 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_user_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(default="static 'img/user_default.jpg' ", upload_to='profile_pic/'),
        ),
    ]
