# Generated by Django 4.1.3 on 2022-12-01 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_detail',
            field=models.TextField(default='null'),
        ),
    ]
